#!/usr/bin/env groovy

//ENV vars
def TOOLS_NAMESPACE = "OpenShift 201 andrea-williams (tools)"
def DEV_NAMESPACE = "OpenShift 201 andrea-williams (dev)"
def PROD_NAMESPACE = "OpenShift 201 andrea-williams (prod)"
def LOKI_SERVICE = "loki"

// Pipeline
node {
    stage ('Build Stage') {
        dir ('simple_pipeline') {
            checkout scm
            sh "oc get projects"
        }
    }
    stage ('Deploy Loki to Dev') {
        dir ('simple_pipeline') {
            checkout scm
            sh "oc process -f openshift201/templates/openshift_loki_template.yaml -p  LOKI_SERVICE_NAME=${LOKI_SERVICE} | oc apply -f - -n ${DEV_NAMESPACE}"
            sh "echo Wait for service to be up"
            timeout (time: 180, unit: 'SECONDS') {
                openshift.withCluster() {
                    openshift.withProject("${DEV_NAMESPACE}") {
                        def dc = openshift.selector('deployment', "${LOKI_SERVICE}")                
                        // this waits until desired replicas are available
                        dc.rollout().status()
                    }
                }
            }
         } 
    }
}
  
