#!/usr/bin/env groovy

//ENV vars
def TOOLS_NAMESPACE = "OpenShift 201 andrea-williams (tools)"
def DEV_NAMESPACE = "OpenShift 201 andrea-williams (dev)"
def PROD_NAMESPACE = "OpenShift 201 andrea-williams (prod)"
def LOKI_SERVICE = "loki"

// Pipeline
node {
    stage ('Build Stage') {
        dir ('simple_pipeline') {
            checkout scm
            sh "oc get projects"
        }
    }
    stage ('Deploy Loki to Dev') {
        dir ('simple_pipeline') {
            checkout scm
            sh "oc process -f openshift201/templates/openshift_loki_template.yaml -p LOKI_SERVICE_NAME=loki-service | oc apply -f - -n 4zq6uj-andrea-williams-ocp201-tst-dev"
            sh "echo Wait for service to be up"
            openshiftVerifyService apiURL: '', authToken: '', namespace: "4zq6uj-andrea-williams-ocp201-tst-dev", svcName: "loki-service", verbose: 'false'
        }
    }
}
  
